SSL option, .env file settings and custom llama path
keldenl/gpt-llama.cpp pull request #16
Opened 2023-04-22 09:48 UTC by cryptocake

- Added SSL functionality, this can be enabled or disabled using the new .env file.
- Custom SSL certs can be added or use the one already provided in `cert/`.
- You have to set your llama.cpp installation directory in the .env file (required action).
- You can now choose which port gpt-llama.cpp will listen to.
- README.md now contains the additional installation steps regarding `.env`.

2023-04-22 20:20 UTC, keldenl requested changes
left some comments

2023-04-22 20:20 UTC, keldenl commented on .env.template
> +LLAMA_PATH="/mnt/set/this/to/llama.cpp"
i actually avoided this so we can put this in the API KEY. less work for the end user to set up. i would prefer if we didn't move the llama_path to .env for now

2023-04-22 20:20 UTC, keldenl commented on .env.template
> +################################################################################
can we add some directions here that tells the user to copy this into their own .env file?

2023-04-22 20:20 UTC, keldenl commented on README.md
> +3. Configure GPT-LLAMA:
lets remove the llama_path instructions

2023-04-22 20:20 UTC, keldenl commented on cert/cert.crt
> +-----BEGIN CERTIFICATE-----
is pushing cert and private key the best thing we can do for security? doesn't seem like a good idea. what are our alternatives?

2023-04-22 20:20 UTC, keldenl commented on routes/chatRoutes.js
> -	const llamaPath = getLlamaPath(req, res);
same comment about llamapath

2023-04-22 20:20 UTC, keldenl commented on routes/embeddingsRoutes.js
> +	const llamaPath = getLlamaPath();
same comment about llamapath

2023-04-22 20:20 UTC, keldenl commented on utils.js
> +export const getLlamaPath = () => {
same comment about llamapath

2023-04-22 20:20 UTC, keldenl commented on utils.js
> +}
do we ever need this? if this is false it should fail on index.js already right?

2023-04-25 15:13 UTC, cryptocake commented
The changes in this PR are obsolete now. Closing.

2023-04-25 15:13 UTC, closed without merging